project:
  type: website
  render:
    - "*.qmd"  
    - "!notebooks/"

website:
  title: "Sand Tracer"
  site-url: https://PythiaEnergy.github.io/raycast-demo/
  favicon: images/logo_pythia.png
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    left: "&copy; 2024 HKV. All rights reserved."
 
  navbar:
    logo: images/logo_pythia.png
    background: "#FBF1CF"
    foreground: "#1F6F65"
    href: https://hkv-products-services.github.io/SandTracer/
    left:
    - text: "Getting Started"
      href: getting_started.qmd    
    - text: "RayCast explained"
      href: raycast_explained.qmd
    - text: "FAQ" 
      href: faq.qmd
    right:
    - icon: github
      href: https://github.com/PythiaEnergy/raycast-demo

format:
  live-html:
    theme: [custom.scss]
    toc: true
    toc-title: Contents
    toc-location: left
    mainfont: "Google Sans Text"
    fontcolor: "#41464a"