project:
  type: website
  render:
    - "*.qmd"  
    - "!notebooks/"

website:
  title: ""
  site-url: www.raycast.nl
  favicon: images/logo_pythia.png
  
  # page-footer: 
  #   right: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
  #   left: "&copy; 2024 HKV. All rights reserved."
 
  navbar:
    logo: images/logo_pythia.png
    background: "#FBF1CF"
    foreground: "#1F6F65"
    href: https://PythiaEnergy.github.io/raycast-demo/
    left:
    - text: "Getting Started"
      href: getting_started.qmd   
    - text: "RayCast explained"
      href: raycast_explained.qmd
    - text: "FAQ" 
      href: faq.qmd
    - text: "Contact" 
      href: contact.qmd
    right:
    - icon: github
      menu:
        - text: Source code
          href: https://github.com/PythiaEnergy/raycast-demo
        - text: Report a Bug
          href: mailto:info@pythia-energy.nl

format:
  html:
    theme: [custom.scss]
    toc: true
    toc-title: Contents
    toc-location: left
    mainfont: "Google Sans Text"
    fontcolor: "#41464a"
